# Makefile for gmake on SGI
#  Copyright (C) 1998, NINTENDO Co,Ltd, MONEGI CORPORATION.

# Usually, modify values for MODULE and SRCS.
MODULE		=	mgk
SRCS		=	app.c \
			obj.c

include ../../common.sgi
