#!/bin/sh
NIFFDIR=${NIFFDIR:=/usr/local/n64kit/niff}
if [ $# = 0 ]; then
  model=$NIFFDIR/nvfview/model.niff
else
  model=$1
fi
cd $NIFFDIR/nvfview
./niff2nvf $model model.nvf
./nvf2bin scene.nvf model.nvf nvfview.bin
nload -n -e nvfview.N64
nload -n -s 0x200000 nvfview.bin
