#include <ultra64.h>
#if 0
#include <sched.h>
#include "misc.h"
#include "simple.h"
#include "audio.h"
#include "gfx.h"
#include <pr\abi.h>
#include <pr\audiotools.h>
#include <pr\dbgdefs.h>
#include <pr\dbgproto.h>
#include <pr\driverd.h>
#include <pr\em.h>
#include <pr\fog_mode.h>
#include <pr\gbi.h>
#include <pr\gs2dex.h>
#include <pr\gt.h>
#include <pr\gtoff.h>
#include <pr\gu.h>
#include <pr\libaudio.h>
#include <pr\libnos.h>
#include <pr\mbi.h>
#include <pr\ncode.h>
#include <pr\os.h>
#include <pr\os_internal.h>
#include <pr\primage.h>
#include <pr\r4300.h>
#include <pr\ramrom.h>
#include <pr\rcp.h>
#include <pr\rdb.h>
#include <pr\region.h>
#include <pr\rmon.h>
#include <pr\rsp.h>
#include <pr\rsp_ipc.h>
#include <pr\sched.h>
#include <pr\sp.h>
#include <pr\sptask.h>
#include <pr\sptaskoff.h>
#include <pr\trace.h>
#include <pr\ucode.h>
#include <pr\ucode_flatfog.h>
#include <pr\ultraerror.h>
#include <pr\ultralog.h>
#include <pr\ultratypes.h>
#include <pr\verify.h>
#endif